FROM vvakame/review:5.0

# Install Redpen modules (In default, textlint module is enabled.)
# RUN mkdir -p /usr/share/man/man1mkdir -p /usr/share/man/man1 \
#   && apt-get update && apt-get install -y wget openjdk-11-jre-headless:amd64 \
#   && wget https://github.com/redpen-cc/redpen/releases/download/redpen-1.10.3/redpen-1.10.3.tar.gz \
#   && tar xvf redpen-1.10.3.tar.gz \
#   && mkdir -p /user/local/redpen \
#   && mv redpen-distribution-1.10.3 /usr/local/redpen

# ENV PATH="/usr/local/redpen/bin:${PATH}"

